### ISSUE TITLE
ARM cloud server

### ISSUE THREAD

**Issue by mkhleel** [chrishubert/whatsapp-api#44]
In Ampere A1 Compute

I got this message

ERROR: for app  no matching manifest for linux/arm64/v8 in the manifest list entries
ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries

**Comment by chrishubert** [comment]
Please try to add `platform: linux/x86_64` in your docker-compose file:
```
version: '3.8'

services:
  app:
    container_name: whatsapp_web_api
    platform: linux/amd64
    image: chrishubert/whatsapp-web-api:latest
    ports:
      - "3000:3000"
    ...
```
