### ISSUE TITLE
Docker Builds versioning

### ISSUE THREAD

**Issue by pilganchuk** [chrishubert/whatsapp-api#60]
Hi @chrishubert, first of all - thx for your solution, it's good!

But, could you please add some tags for the builds on Docker Hub?
Smth like this:
```
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags:  | 
             'chrishubert/whatsapp-web-api:latest'
             'chrishubert/whatsapp-web-api:${{ env.SHORT_REF_NAME }}_${{ env.SHORT_SHA }}
```

It will be more convenient to use on K8S.
